### ISSUE TITLE
WHY DOES TURTLECOIN NOT WORTK

### ISSUE THREAD

**Issue by fexra** [Jachi84/PinkstarcoinV2#6]
HELLO,M

I JUST Downloaded Your Latest Vuerson of  the BLOCKCHGAIN & i wanted to put my Garndma on

gowHEver,,,,,,, i heard dat TURTLER COIN IS only for the  SMART aanD  TRAINED.

PLEASE help me isntall TURTLECOIN.,. i thhought this was TURLTE COIN

BUT IT ISNT!!! THIS IS NOT TURTLECOIM. ITS SHITCOPIMN

PLZ give me credit

**Comment by crappyrules** [comment]
@Jachi84 **SIRS, WEN LAMBO??**
https://www.youtube.com/watch?v=Snq6hx2IK48
